### ISSUE TITLE
Compatibility with Grav + Gantry Framework

### ISSUE THREAD

**Issue by paulhibbitts** [bleutzinn/grav-plugin-add-page-by-form#10]
When using the Add Page by Form plug with Grav plus the Gantry Framework (in this case using the Hydrogen theme) the SimpleMDE editor toolbar does not appear in the content area as expected, as shown here:
![2017-01-09_14-32-04](https://cloud.githubusercontent.com/assets/1812771/21815243/cdbe0616-d710-11e6-9d2f-30f76fcf10e4.png)

Thanks very much,
Paul

**Comment by bleutzinn** [comment]
Gantry5 does not load jQuery by default. It can, but it's optional.
The Add Page By Form plugin requires jQuery so jQuery is now included as an Asset.

**Comment by paulhibbitts** [comment]
Thanks Ron, I will test this with Gantry once the new release is available.
