### ISSUE TITLE
Documentation: Location of thankyou/formdata.md in modular pages

### ISSUE THREAD

**Issue by rkammann** [bleutzinn/grav-plugin-add-page-by-form#14]
Could you indicate in the documentation where thankyou/formdata.md needs to be located in modular page setups, and how to reference this location in the form definition of the modular.md file, where a full path might be required? Also, if a full path is required, what is this full path in 'multilingual' sites that may have a language token (fr, de, etc.) in the path? Thanks!

**Comment by bleutzinn** [comment]
I'll look into both. If I understand correctly you the page with the "Add Page form" is a modular page?

**Comment by rkammann** [comment]
Thanks! Actually, however, this isn't about the Add Page by Form plugin. I'm just trying to get a plain comment form working as part of a vanilla modular page that doesn't act in ways predicted by the main Grav documentation. When opening this thread here, I was shooting from the hip, following up from a previously closed similar issue raised around here, without even checking where I was posting the issue. Please ignore this thread, and sorry for the bother!

**Comment by bleutzinn** [comment]
Thanks for the heads up! No problem.
