### ISSUE TITLE
Insert images after uploading files

### ISSUE THREAD

**Issue by mtobeiyf** [bleutzinn/grav-plugin-add-page-by-form#15]
Thanks for your version 1.40!
Are there any easy ways to insert an image file after uploading a file? Like the insert/delete buttons in Admin panel.
By the way, when will this version be officially published?

**Comment by bleutzinn** [comment]
For users who may fill in and submit the form but do not have access rights to the Admin panel, there is no way of controlling where on the new page the images should be displayed. That is completely up to the theme template to be used. For example when `template: item` is set in the pagefrontmatter block then the theme's template `blog_item.html.twig` determines how the uploaded images are displayed in the new blog post.
You could override the template setting by using a select field in the form so the user can select the kind of page/post he or she wants to add. Each select should be coupled to a different template.

**Comment by bleutzinn** [comment]
Just released version 1.4.1.
