### ISSUE TITLE
File Uplaods to New Page

### ISSUE THREAD

**Issue by metadiv** [bleutzinn/grav-plugin-add-page-by-form#19]
Hi,

Im just curious if you know of a way to route file uploads using the file type form field to the newly created page rather than having to push them all to a single predefined folder?

Any advice would be a appreciated!

**Comment by bleutzinn** [comment]
I'm not sure what you mean by "file type form field".
Assuming you are referring to the [Frontend Forms File Field](https://learn.getgrav.org/forms/forms/fields-available#the-file-field) do you mean that the file should be stored in a folder determined upon the MIME type of the file?

**Comment by metadiv** [comment]
Sorry, let me clarify..

I have a front end form that contains a type: file field. and the action addpage: null
 my page structure is:

Parent-Page
    - Archive-Page(parent for new pages)
        - New-Page
    - Form-Page (front end form to create new page with)

If I set the destination of the file field to @self when the form is submitted it uploads the files to theForm-Page folder.

My question is how do I get the file to upload to the New Page folder instead of leaving them in the Form-Page folder

**Comment by bleutzinn** [comment]
Can you please test using the latest version of the plugin? About a month ago I changed the destination of '@self' to be the new page folder.

**Comment by metadiv** [comment]
Using v1.3.1. Only started playing with this at the beggining of last week.

**Comment by bleutzinn** [comment]
You are right. Version 1.3.1 is (or rather was) the latest release. The version with the file upload support was still in a dev branch and was therefor not downloadable on the Grav website.
I made a new release and it should be available in the Plugins section soon. If that takes too long you can download it from GitHub and install it manually.
Thanks for using the plugin!
