### ISSUE TITLE
Uploaded images are not moved to the destination folder in some cases

### ISSUE THREAD

**Issue by charlesknightsbridge** [bleutzinn/grav-plugin-add-page-by-form#20]
I have put my new-article form in a subfolder (/user/pages/07.members/new-article/form.md) and have 
destination = '@self'

Line 249 of add-page-by-form.php checks for 'user/pages/new-article' in the string 'user/pages/07.members/new-article/xyz.jpg' and always fails. I am not totally clear on why the if statement is there, but if I change it to

if (strpos($destination, $folder) !== false) {

images are copied to the real destination path.

**Comment by bleutzinn** [comment]
Thanks for pointing at this. The code did not allow for forms to be anywhere else than in the page root.
I'm planning on reworking this plugin and since your solution solves the issue for now I'm closing this issue.

**Comment by charlesknightsbridge** [comment]
Thanks. I had not realized this and decided to have all submitted documents go to a hidden folder. I could easily have them stay in the same folder as the form, as they are not published.
