### ISSUE TITLE
Activate via Class instead of ID

### ISSUE THREAD

**Issue by Duke3D** [bleutzinn/grav-plugin-add-page-by-form#21]
The Readme says:
When a textarea field is given the id simplemde then it will activate the SimpleMDE Markdown Editor.

Some content types have more than one textarea that can be benefited by having the Editor triggered.
Would it make sense for the editor to be triggered to apply to a textarea with the **class** simplemde so that more than one instance of an editable textarea can be rendered per page and/or single instances where the id is being specified differently to launch field-specific post-processing in another plugin?

**Comment by bleutzinn** [comment]
It's on the roadmap for the next version.

**Comment by bleutzinn** [comment]
From version 2 onwards to make a textarea field use the markdown editor add the class "editor". See the example forms.
