### ISSUE TITLE
Display page not found

### ISSUE THREAD

**Issue by Remedez** [bleutzinn/grav-plugin-add-page-by-form#22]
I keep experiencing an issue about the display age not found after submitting the blog post. Everything work fine until i click submit, the post work but the submit button redirect me to an error.

Server Error
Sorry, something went terribly wrong!

400 - Display page not found. Please check the page exists.

For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

Here the error, i tried all combination possible of the path of my thankyou page, but nothing works. I use a configuration of multisite with subfolder in GRAV, wonder if that error could be from that point? Please let me know on how to correct this issue. 
Thanks in advance

**Comment by bleutzinn** [comment]
In your multi site setup, does a normal form successfully show the display page? With a normal form I mean a form which doesn't use this plugin.

**Comment by Remedez** [comment]
Sorry for the delay...
Yes the normal form is perfectly working on it... and the display page is working

**Comment by bleutzinn** [comment]
Of this is still an issue with verstond 2.0 please re-open this issue.
