### ISSUE TITLE
Direct to newly created page after submission

### ISSUE THREAD

**Issue by GeorgesPapas** [bleutzinn/grav-plugin-add-page-by-form#23]
Hi there,

I'm wondering how I would go about getting the user redirected to the newly created page after a successful submission, rather than the 'thank-you' page. I've tried to change the value of the display field but I can't seem to find a variable that contains the newly created page slug.

Thanks.

**Comment by bleutzinn** [comment]
The slug is created after the submit when the form is processed by the plugin. Maybe it's possible to define `display: @self` which gets substituted by the new page's slug.
 I'll look into it.

**Comment by bleutzinn** [comment]
This is possible from V2.0.0 by using 'redirect: @self'.
