### ISSUE TITLE
Settings Don't Match

### ISSUE THREAD

**Issue by bobrocke** [bleutzinn/grav-plugin-add-page-by-form#35]
The Add Page By Form Admin interface looks like this:

![2019-01-31 at 10 03 am](https://user-images.githubusercontent.com/2962426/52062956-85d4e480-253f-11e9-98d0-04d47879cbf9.jpg)

The default YAML shows this:
```
enabled: true
date_display_format: 'd-m-Y g:ia'
default_title: 'My New Page'
default_content: 'No content.'
overwrite_mode: false
include_username: false
auto_taxonomy_types: false
```

The user config YAML shows this:
```
enabled: true
date_display_format: 'd-m-Y g:ia'
default_title: 'My New Blog Post'
default_content: 'Type the blog post content here.'
overwrite_mode: false
include_username: false
auto_taxonomy_types: true
```
Why doesn't the admin interface match the active (user config) settings?

**Comment by bleutzinn** [comment]
I can't confirm your observation.

The user config YAML is stored in `user/config/plugins/add-page-by-form.yaml`.
If I open that file in a text editor, change a setting, save the file and refresh the plugin config page in Admin I see my changes there as well. Also the other way around works fine.

BTW This is all handled by the Admin plugin only.

**Comment by bobrocke** [comment]
OK, I'm good. I may have missed refreshing the Admin page. It works for me as you suggest.

Thanks for the help.
