### ISSUE TITLE
Changing the folder name slug?

### ISSUE THREAD

**Issue by bobrocke** [bleutzinn/grav-plugin-add-page-by-form#36]
I'm setting up this plug-in to create blog posts.

I'd like to take the default folder name slug (the slugified blog post title) and add the date in front of it in this format:

`2019-01-31-blog-post-title`

Is there a configuration field for that? Where would I go to make that change to default behavior?

**Comment by bleutzinn** [comment]
Setting the new page slug is quite flexible but setting it by concatenating values can't be done without modifying the plugin. In [add-page-by-form.php#L344](https://github.com/bleutzinn/grav-plugin-add-page-by-form/blob/3c6cdeaac7fa72873d1dc5f086d4b85fcd9c55ee/add-page-by-form.php#L344) you can change or set any frontmatter variable you want.

Assuming you've already set the `slug_field` variable to the form field for your blog post title you could add this line there:
```
$page_frontmatter['slug'] = date("Y-m-d") . '-' . $this->sanitize($page_frontmatter[$slug_field], 'slug');;
```

**Comment by bobrocke** [comment]
Using this at line 345:
`$page_frontmatter['slug'] = date("Y-m-d") . '-' . $this->sanitize($page_frontmatter['title'], 'slug');`
and inputs for Author, Post bTitle, and Post Content (defaulting Tags), I get: ERROR: array_merge(): Argument #1 is not an array

I must have missed something?

**Comment by bobrocke** [comment]
I have the same error when I use:
` $page_frontmatter['slug'] = date("Y-m-d") . '-' . $this->sanitize($page_frontmatter[$slug_field], 'slug');`

**Comment by bobrocke** [comment]
I had `auto_taxonomy_types: true` as opposed to the default `auto_taxonomy_types: false`. Once set back to the default, the error didn't happen and I got the behavior you described.

What, exactly, is `auto_taxonomy_types:` doing? I want to be able to enter potentially new taxonomy types on the form and have them created on the site.

The files generated, using your input examples are a new folder named `rt2` with a file named `default.md` in it.

What I'm after is a folder named `2019-02-03-rt2` and a file named `item.md`. What should I change to get that?

**Comment by bleutzinn** [comment]
The `auto_taxonomy_types` should be doing what you expect: create new taxonomy types on the form and have them created on the site. It does not add them to the `site.yaml` config file though. That's a bug ( issue [#37](
https://github.com/bleutzinn/grav-plugin-add-page-by-form/issues/37l)).

When doing things the "Grav-way" there is no need to set the page folder name nor the page filename to anything different than normal.

To handle entries with identical blog post titles first make sure the setting `overwrite_mode` (in the plugin config and/or in the form page) is set to `false`.
As is the plugin will add a sequential number when creating pages with the same blog post title (in the form field `title`).

If you must set the folder name this can be done by changing the extra code to:
```
$page_frontmatter['slug'] = date("Y-m-d") . '-' . $this->sanitize($page_frontmatter['posttitle'], 'slug');
$slug = $page_frontmatter['slug'];
```

So make sure to have a field named `posttitle` and there is NO `title` field or variable in play.

The name of the page filename is used by Grav to 'know' the template name but that is overruled if there's a variable `template` set in the page frontmatter. There is no easy hack to set the filename to anything else then `default`. And there really is no need, simply add
```
template: item
```
in the new page frontmatter.

**Comment by bobrocke** [comment]
OK, I've gone a bit past ordinary configuration and changed the code such that I get folder names and filenames to my taste. I do like doing things "the grav way" whenever possible. For me, I use the folder name, although somewhat arbitrary to Grav, as a chronological mechanism for my blog posts:

![2019-02-03 at 1 10 pm](https://user-images.githubusercontent.com/2962426/52180506-241db000-27b5-11e9-9de8-78654b155131.jpg)

If I don't want to create new taxonomy types on the form, will adding new taxonomy items work fine? For example, I may have a Taxonomy Type of `count` with items `[one, two, three]`. Can I enter item `four` on the form and have it handled properly?

In the event that you make a version change to the plug-in, please consider some configuration options to allow choosing a file name (with default.md as the reasonable default) and a folder name? To get my concatenated folder name would still require a code change. Perhaps allow a custom function that could be defined in a separate `.php` file to generate folder names?

**Comment by bobrocke** [comment]
Thanks for the help through this. I think I understand the plug-in better and have it doing what I needed.

Your development style sounds a lot like mine, but your code is more advanced.

I don't know of an example plug-in with a custom function. But the "real" developer community is very helpful and the Grav folks are happy to help, too. If you are not on the Grav channel on Discord, it's a great place to start with questions.
