### ISSUE TITLE
dont work in GRAV 1.6.8

### ISSUE THREAD

**Issue by abooks23** [bleutzinn/grav-plugin-add-page-by-form#40]
Hi !
dont work in GRAV 1.6.8

images dont move, but is in tmp dir

**Comment by abooks23** [comment]
Hi! please correct, is very necessary

**Comment by bleutzinn** [comment]
This appears to be difficult to fix. Changes in the latest Form plugin conflict with the correct working of this plugin. I posted in the Grav developers chat and hope someone can help.

**Comment by abooks23** [comment]
ok, )

**Comment by bleutzinn** [comment]
Can you please test a new version that works with Grav v1.6.9 and Form plugin v3.0.3 ?

You can download the fixed PHP file from https://warden.stackstorage.com/s/kSd1XeOGWlrW54f
After downloading save `add-page-by-form.php` in `user/plugins/add-page-by-form/` overwriting the existing `add-page-by-form.php` file.

Please let me know if this fix works for you.

**Comment by thomasporhel** [comment]
Hi!

This fixed it for me, it now works perfectly. What a great plugin, thanks for this (-:

**Comment by abooks23** [comment]
Hi
work fine, thanks
but need to change '`Parameter separator`' to `:` (i run site on locahos windows...)

**Comment by bleutzinn** [comment]
Can you explain the problem in more detail? What tool do you use to search?

The default `Parameter separator` in Grav is `:`. The plugin does not change the default setting, no matter what operating system you use Grav on. Please elaborate.

**Comment by abooks23** [comment]
Hi 
I switch `Parameter separator` to` ;` because i run windows on localhost, with` : `i see this:
![Без имени-1](https://user-images.githubusercontent.com/27723595/59006073-d2e80080-8828-11e9-8076-90b118eac574.jpg)
I think this is a problem plugin form, on real host work fine. I use simplesearch, after update 1.6.9 does not work....
in localhost with `Parameter separator :` I getting 404 error

**Comment by bleutzinn** [comment]
To test this you can simply disable the Add Page plugin under Plugins in the Admin panel or remove the plugin. Simply use the form again and see if the upload succeeds (a checkmark appears) or fails (a cross is shown). If it fails then it is a bug in the Form plugin or Grav core.

**Comment by abooks23** [comment]
i test search in new 1.6.9 - rezult = 0
test in 1.6.8 with form 2.16.2 - work ok
test in 1.6.8 with form 3.03 - error
I post problem in Grav form
this topic may be closed)
thanks!
sorry for my english))

**Comment by bleutzinn** [comment]
Your English is much much better than my Russian ;)

**Comment by abooks23** [comment]
Hi
now all work fine)
but in 1.6.8, apparently problem in grav.
thanks
