### ISSUE TITLE
Files Uploaded to the form's directory instead of the new page's directory

### ISSUE THREAD

**Issue by jwillp** [bleutzinn/grav-plugin-add-page-by-form#46]
A Client of mine noticed that in some cases the files were not uploaded.
After digging a bit I discovered that files were actually uploaded to the wrong location.
Instead of being moved to the new page's directory, they were uploaded to the form's directory and kept there.

The offending lines are these ones:
https://github.com/bleutzinn/grav-plugin-add-page-by-form/blob/9f403569a1b336e7f8cbaadf26e82ac81bf1fddc/add-page-by-form.php#L92-L99

Changing the line as follows seems to fix the issue: 
```php
 $full_name = $new_page_path . DS . $file_name; 
copy($tmp_file, $full_name); 
```
When letting the Form plugin handle the move, it seems to actually think that the final destination
of the file is where the form is located.

Now I am sure there is a specific reason for letting the Form Plugin handle the move in some cases, but I haven't found it in any of the documentation.

@bleutzinn, could you provide details on why this check is made and what it entails?

Thank you :)

**Comment by bleutzinn** [comment]
Solved by #47.
