### ISSUE TITLE
Missing slug field deletes the whole folder

### ISSUE THREAD

**Issue by anton-mellit** [bleutzinn/grav-plugin-add-page-by-form#52]
Suppose slug_field is given but for some reason the corresponding field is empty. Or suppose title is empty. In these cases the plugin will **delete the whole parent folder**. I think this is very dangerous (this happened to me, fortunately I had a backup).

I don't know if this is the intended behavior. In my copy I added
```
if (empty($slug)) {
    throw new \RuntimeException('Empty slug for a new page. Prevented deleting the whole folder.');
}
```

**Comment by bleutzinn** [comment]
Fixed in release 2.4.1
I've changed the exception into a form validation error message.

Thanks for reporting.
