### ISSUE TITLE
$overwrite_mode conditionals are not using string comparisons

### ISSUE THREAD

**Issue by mooomooo** [bleutzinn/grav-plugin-add-page-by-form#54]
Handling overwrite_mode seems to be entirely broken, in large part because of conditionals that don't use string comparisons.  Things like `if($overwrite_mode)` (line 315, 549, etc.) get triggered when `$overwrite_mode` is the string `'false'`.  There may also be other places where the expected behavior fails, I'm guessing for similar reasons.

**Comment by bleutzinn** [comment]
Thanks for reporting this. In the ["overwrite_mode_fix" branch](https://github.com/bleutzinn/grav-plugin-add-page-by-form/tree/overwrite_mode_fix) there's a changed "add-page-by-form.php" file.

If you can test it and let me know I would really appreciate it! Thank you.

**Comment by mooomooo** [comment]
Thanks for your prompt attention!  

You deleted `$positives`, but it's still referenced in lines 375, 384 which is causing problems.

**Comment by bleutzinn** [comment]
I put `$positives` back in. Sorry about that.

**Comment by mooomooo** [comment]
I haven't exhaustively tested all possible use cases, but I haven't run across any more issues.  Thanks!

**Comment by bleutzinn** [comment]
Merged into master. Thank you.
