### ISSUE TITLE
redirect: '@self' doesn't include the websites url, only relative link

### ISSUE THREAD

**Issue by maxroseGIT** [bleutzinn/grav-plugin-add-page-by-form#59]
Hi,
first, thanks a lot for this very useful plugin!

Before I start to dig into your code I wanted to tell you the following issue I came accross.

I tested the plugin with your example 2 'create a blog post' and when I submit the new page the redirected page shown in the browser gives me just a 
`http://my-new-blog-post/`
when I use the `@self` redirection option.

A similar this happens with the `@self-admin` option. It gives me this redirection:
`http://baseURL.tpl/admin/pages//my-new-blog-post`

Somehow the base url of the website is lost in the redirection.

You got any idea why this happens?

(BTW redirection to a folder like `/blog` works fine)

I use `Add Page By Form v3.0.3` and `Grav v1.7.9 - Admin v1.10.8`

**Comment by bleutzinn** [comment]
Yes, creating new pages in the web root is currently a limitation or bug. Though I tried to have the plugin support that I couldn.'t make it work. Feel free to 'dig into the code' and a pull request would be very welcome!
