### ISSUE TITLE
Question: Any way to add date to newly created pages?

### ISSUE THREAD

**Issue by therealgorgan** [bleutzinn/grav-plugin-add-page-by-form#60]
Hi there, I use this plugin to let others easily add news articles to our website, and unfortunately, when we edit the pages the date is changed and I was looking to have the this plugin set the date frontmatter upon creation. I thought about adding a date field and then having JS populate the field, but wondered if it was possible in the plugin itself? Thanks!

**Comment by bleutzinn** [comment]
Cool to read how you use the plugin. To add the current date when the article is created you can use another of my plugins: https://github.com/bleutzinn/grav-plugin-form-prefiller

In the README you’ll also find a way do do it without the Form Prefiller plugin. So you can choose which method you like best.
