### ISSUE TITLE
If the Title field contains diacritics, the form submission will fail

### ISSUE THREAD

**Issue by petira** [bleutzinn/grav-plugin-add-page-by-form#61]
If the **Title** field contains diacritics (e.g. ě, č, ř, ž, ý, á, í, é etc.), the form submission will fail:

**ERROR** in Add Page by Form Plugin: Variable 'slug' is empty

**Comment by bleutzinn** [comment]
Actually this problem was [fixed](https://github.com/bleutzinn/grav-plugin-add-page-by-form/commit/f7ded57d50d8f246bf2601edacf8be3238ea9691) long time ago. For some reason that change hasn't lead to a new release.
I'll make a v3.0.4 release soon if time permits.

**Comment by bleutzinn** [comment]
Closing due to fixed in release v3.0.4.
